"""Add committed_amount to analytics

Revision ID: 0a00c9fac638
Revises: 8d4e01cd8f1f
Create Date: 2025-07-18 15:40:10.023010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a00c9fac638'
down_revision = '8d4e01cd8f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committed_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('committed_amount')

    # ### end Alembic commands ###
