"""Add bot_ui_mandays and custom_ai_mandays to Analytics

Revision ID: 16681e330ae8
Revises: 18e46c619863
Create Date: 2025-07-08 08:47:35.522482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16681e330ae8'
down_revision = '18e46c619863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_ui_mandays', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custom_ai_mandays', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('custom_ai_mandays')
        batch_op.drop_column('bot_ui_mandays')

    # ### end Alembic commands ###
