"""add bot_ui_manday_rate and custom_ai_manday_rate to analytics

Revision ID: 18e46c619863
Revises: c830e8f58cd7
Create Date: 2025-07-08 00:28:06.366052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e46c619863'
down_revision = 'c830e8f58cd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bot_ui_manday_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('custom_ai_manday_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('custom_ai_manday_rate')
        batch_op.drop_column('bot_ui_manday_rate')

    # ### end Alembic commands ###
