"""add calculation_id to analytics

Revision ID: 551bfe56e171
Revises: 16681e330ae8
Create Date: 2025-07-09 18:25:55.706790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551bfe56e171'
down_revision = '16681e330ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_id', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('calculation_id')

    # ### end Alembic commands ###
