"""Add currency column to analytics

Revision ID: 8568a5b71b0a
Revises: f97cb127d875
Create Date: 2025-07-01 12:24:14.298028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8568a5b71b0a'
down_revision = 'f97cb127d875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('bot_ui_manday_rate', sa.Float()))
        batch_op.add_column(sa.Column('custom_ai_manday_rate', sa.Float()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('currency')
        batch_op.drop_column('bot_ui_manday_rate')
        batch_op.drop_column('custom_ai_manday_rate')

    # ### end Alembic commands ###
