"""add calculation_route to analytics

Revision ID: 8d4e01cd8f1f
Revises: 551bfe56e171
Create Date: 2025-07-16 11:45:17.679737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4e01cd8f1f'
down_revision = '551bfe56e171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_route', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('calculation_route')

    # ### end Alembic commands ###
