"""Initial migration

Revision ID: 9f7897f373d9
Revises: 
Create Date: 2025-06-30 22:18:06.090738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7897f373d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('platform_fee', sa.Float(), nullable=True),
    sa.Column('ai_price', sa.Float(), nullable=True),
    sa.Column('advanced_price', sa.Float(), nullable=True),
    sa.Column('basic_marketing_price', sa.Float(), nullable=True),
    sa.Column('basic_utility_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    # ### end Alembic commands ###
