"""Add voice notes columns to analytics

Revision ID: add_voice_notes_columns
Revises: 0a00c9fac638
Create Date: 2025-09-22 12:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_voice_notes_columns'
down_revision = '0a00c9fac638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_notes_price', sa.String(8), nullable=True))
        batch_op.add_column(sa.Column('voice_notes_model', sa.String(64), nullable=True))
        batch_op.add_column(sa.Column('voice_notes_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('voice_notes_rate')
        batch_op.drop_column('voice_notes_model')
        batch_op.drop_column('voice_notes_price')

    # ### end Alembic commands ###
