"""add advanced analytics fields to Analytics model

Revision ID: c830e8f58cd7
Revises: 8568a5b71b0a
Create Date: 2025-07-03 23:31:14.421397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c830e8f58cd7'
down_revision = '8568a5b71b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_rate_card_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advanced_rate_card_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('basic_marketing_rate_card_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('basic_utility_rate_card_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('advanced_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('basic_marketing_volume', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('basic_utility_volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.drop_column('basic_utility_volume')
        batch_op.drop_column('basic_marketing_volume')
        batch_op.drop_column('advanced_volume')
        batch_op.drop_column('ai_volume')
        batch_op.drop_column('basic_utility_rate_card_price')
        batch_op.drop_column('basic_marketing_rate_card_price')
        batch_op.drop_column('advanced_rate_card_price')
        batch_op.drop_column('ai_rate_card_price')

    # ### end Alembic commands ###
